### ISSUE TITLE
No gem published? Missing tag?

### ISSUE THREAD

**Issue by fxn** [zvkemp/rb-phoenix-socket#7]
Is this gem published?

```
% gem install rb-phoenix-socket -N
ERROR:  Could not find a valid gem 'rb-phoenix-socket' (>= 0) in any repository
```

On the other hand, is the repo missing a tag for 0.3.2?

**Comment by zvkemp** [comment]
@fxn No, I never published it (and haven't paid attention to it for a few years now; I haven't tried to use it with recent Phoenix versions).

**Comment by fxn** [comment]
Got it, thanks for the prompt response!
